name: Java build usig reusable
on:
  workflow_dispatch:

env:
  JAVA_VER: "17"

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - name: Running reusable build action for Java app
      - uses: ./.github/actions
        with:
          java-ver: ${{ env.JAVA_VER }}
          app-dir: '.'
          maven-goal: 'package'

      - name: list the build content
        run: | 
          cd ./target/
          ls -lart
